version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:8000
    networks:
      - lobby

  web:
    build: .
    command: python test.py -h 0.0.0.0
    volumes:
      - .:/usr/src/app
    ports:
      - 27713:27713/udp
    networks:
      - lobby

networks:
  lobby:

